### ISSUE TITLE
search does not work on docs

### ISSUE THREAD

**Issue by goern** [thoth-station/nepthys#48]
**Describe the bug**
using https://thoth-station.ninja/docs/developers/adviser/search.html?q=sieve results in a list of results, if I click on any link, it results in a 404

**To Reproduce**
1. Go to https://thoth-station.ninja/docs/developers/adviser/search.html?q=sieve
2. Click on 'thoth.adviser.sieves'

/kind bug
/priority important-soon
/assign @harshad16

**Comment by harshad16** [comment]
Took some time, however, figured out the reason for the issue.
It is causing due to the searchtool.js, which specifics file to be added from `_sources` folder https://github.com/thoth-station/thoth-station.github.io/blob/0bd19640ce3b5caf2b4f7f3b26e04b1bd225bfb6/assets/searchtools.js#L538.

with our changing in sphinx build and moving the files around to support jekyll, all the files are moved to the sources folder.

while checking on this, got to understand we would have to change the logic of moving the file from `_static` to  `assets` directory as some components are getting overwritten.
https://github.com/thoth-station/nepthys/blob/2ac1d8dffbccf73e931b96ea9a3401b9cd0e9e77/create_docs.sh#L66

will be sending in a pull request with the changes. :+1:

**Comment by fridex** [comment]
> Took some time, however, figured out the reason for the issue.
> It is causing due to the searchtool.js, which specifics file to be added from `_sources` folder https://github.com/thoth-station/thoth-station.github.io/blob/0bd19640ce3b5caf2b4f7f3b26e04b1bd225bfb6/assets/searchtools.js#L538.
> 
> with our changing in sphinx build and moving the files around to support jekyll, all the files are moved to the sources folder.
> 
> while checking on this, got to understand we would have to change the logic of moving the file from `_static` to `assets` directory as some components are getting overwritten.
> https://github.com/thoth-station/nepthys/blob/2ac1d8dffbccf73e931b96ea9a3401b9cd0e9e77/create_docs.sh#L66
> 
> will be sending in a pull request with the changes.

Nice! Thanks! :+1:

**Comment by harshad16** [comment]
Fixed with #49
